# Generated by Django 5.1.2 on 2024-11-08 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
